- hosts: servers
  tasks:

  - name: Pull latest Docker image
    community.docker.docker_image:
      name: devdeepsarkar/calculator
      source: pull

  - name: Remove existing container if present
    community.docker.docker_container:
      name: calculator_container
      state: absent
    ignore_errors: yes

  - name: Start new container
    community.docker.docker_container:
      name: calculator_container
      image: devdeepsarkar/calculator
      state: started
      recreate: yes
      tty: true
      interactive: true
      restart_policy: always
      published_ports:
        - "5050:5000"