- hosts: servers
  tasks:

  - name: Pull Docker Image
    docker_container:
      name: calculator_container
      image: devdeepsarkar/calculator
      state: started
      recreate: yes
      ports:
        - "5050:5000"